### ISSUE TITLE
请问大佬 你是使用的官方kdd99的数据吗？

### ISSUE THREAD

**Issue by intbjw** [Bingmang/kddcup99-cnn#1]
请问大佬 你是使用的官方kdd99的数据吗？

**Comment by Bingmang** [comment]
可以看下`data.py`中获取数据的方法：

`sklearn.datasets.fetch_kddcup99()`

根据资料，这个是KDD竞赛在1999年举行时采用的数据集。

**Comment by intbjw** [comment]
嗯嗯 我知道这个数据集 麻烦大佬了 谢谢啦

**Comment by Bingmang** [comment]
不客气，交流愉快😄
